;COUNT s PARTICULAR CHARACTER IN A STRING
;CODE:
	AREA PROGRAM,CODE,READONLY
ENTRY
	LDR R0,=string
LOOP
	LDRB R1,[R0],#0x01
	CMP R1,"s"
	ADDEQ R2,R2,#0x01
	CMP R1,#0x00
	BNE LOOP
	AREA PROGRAM,DATA,READONLY
string DCB "Assembly"
	END
